# Generated by Django 4.2.6 on 2023-11-06 22:23

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('NewApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='padrino',
            name='descripcion',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
