# Generated by Django 4.2.5 on 2023-10-17 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DogsApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='adoptado',
            name='edad',
            field=models.CharField(blank=True, default=0, max_length=2),
        ),
    ]
