# Generated by Django 4.2.6 on 2023-10-20 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DogsApp', '0002_delete_adoptante'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adoptado',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='fotos_adoptados'),
        ),
    ]
