# Generated by Django 4.2.6 on 2023-10-19 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DogsApp', '0003_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='adoptado',
            name='foto',
            field=models.ImageField(default=2, upload_to=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='adoptado',
            name='nacimiento',
            field=models.DateField(default=1),
            preserve_default=False,
        ),
    ]
