# Generated by Django 4.2.6 on 2023-10-19 23:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DogsApp', '0004_adoptado_foto_adoptado_nacimiento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adoptado',
            name='nacimiento',
        ),
    ]
